pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
               // sh 'mvn -f java-tomcat-sample/pom.xml clean package'
               
               bat 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                //build job: 'Deploy_Application_Staging_Env'
                build job: 'deploy-application-to-staging'

            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                //build job: 'Deploy_Application_Prod_Env'
                echo 'build job: Deploy_Application_Prod_Env SKIPPED'
            }
        }
    }
}
